server:
  port: 9999
spring:
  application:
    name: cookbook
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2

---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    driver-class-name: org.h2.Driver